### ISSUE TITLE
Rhino 6 SR 15

### ISSUE THREAD

**Issue by DarrelRonald** [ccc159/CodeListener#1]
Codelistener will not show up in Tools > Plugins  for Rhino v6 sr14 or sr15.
Could you please specify in the releases what version of Rhino 6 and SR# it will work with?
You state that it will only work "with **correct** build being installed." But I cannot find **correct**j defined anywhere.  Thank you.

**Comment by snjsomnath** [comment]
Hi Darrel,
Could you try the steps mentioned in the following link and let me know if it worked for you.
Running through cmd with admin permissions worked for me.
https://wiki.mcneel.com/rhino/installrhi

Cheers

**Comment by jingcheng-chen** [comment]
> Codelistener will not show up in Tools > Plugins for Rhino v6 sr14 or sr15.
> Could you please specify in the releases what version of Rhino 6 and SR# it will work with?
> You state that it will only work "with **correct** build being installed." But I cannot find **correct**j defined anywhere. Thank you.

From Version 0.1.7, codelistener supports Rhino 6. I just tested and it works on Rhino 6 SR 16.

Maybe it's an admin issue as @snjsomnath said.

**Comment by DarrelRonald** [comment]
Thank you for the quick replies. I fortunately got it working, there are no problems with codelistener plugin. It is much nicer to use in comparison to the default Rhino editor!
